# Generated by Django 3.1.12 on 2025-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('out_of', models.IntegerField(default='5')),
                ('review', models.TextField()),
                ('movie', models.IntegerField()),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
